apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-child-clusters
  namespace: rhacm-policies
spec:
  clusterSelector: {}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: deploy-blackbox-exporter
  namespace: rhacm-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: blackbox-exporter-config
      spec:
        remediationAction: enforce
        namespaceSelector:
          include: ["openshift-monitoring"]
        object-templates:
        # 1) ConfigMap cấu hình module cho Blackbox Exporter
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: blackbox-exporter-config
              namespace: openshift-monitoring
              labels:
                openshift.io/cluster-monitoring: "true"
            data:
              blackbox.yaml: |
                modules:
                  http_2xx:
                    http:
                      follow_redirects: true
                      preferred_ip_protocol: ip4
                      valid_http_versions:
                      - HTTP/1.1
                      - HTTP/2.0
                      tls_config:
                        insecure_skip_verify: true
                    prober: http
                    timeout: 5s
        # 2) Deployment Blackbox Exporter
        - complianceType: musthave
          objectDefinition:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: prometheus-blackbox-exporter
              namespace: openshift-monitoring
              labels:
                app: prometheus-blackbox-exporter
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: prometheus-blackbox-exporter
              template:
                metadata:
                  labels:
                    app: prometheus-blackbox-exporter
                spec:
                  containers:
                  - name: blackbox-exporter
                    image: quay.io/prometheus/blackbox-exporter:v0.27.0
                    args:
                    - --config.file=/config/blackbox.yaml
                    ports:
                    - containerPort: 9115
                      name: metrics
                    volumeMounts:
                    - name: config
                      mountPath: /config
                  volumes:
                  - name: config
                    configMap:
                      name: blackbox-exporter-config
        # 3) Service cho Blackbox Exporter
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Service
            metadata:
              name: prometheus-blackbox-exporter
              namespace: openshift-monitoring
              labels:
                app: prometheus-blackbox-exporter
                openshift.io/cluster-monitoring: "true"
            spec:
              selector:
                app: prometheus-blackbox-exporter
              ports:
              - name: metrics
                port: 9115
                targetPort: 9115
        # 4) ServiceMonitor để gọi /probe với 4 endpoint
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: bind-deploy-blackbox-exporter
  namespace: rhacm-policies
placementRef:
  name: all-child-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: deploy-blackbox-exporter
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: hub-only
  namespace: rhacm-policies
spec:
  clusterSelector: {}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: mco-allowlist-probe-metrics
  namespace: rhacm-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: mco-allowlist-probe-metrics-config
      spec:
        remediationAction: enforce
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: observability-metrics-custom-allowlist
              namespace: open-cluster-management-observability
            data:
              metrics_list.yaml: |
                names:
                  - probe_success
                  - probe_duration_seconds
                  - probe_http_status_code
                  - probe_http_duration_seconds
                  - probe_http_redirects
                  - probe_http_content_length
                  - probe_ip_protocol
                  - probe_dns_lookup_time_seconds
                  # bổ sung nếu cần thêm các metric khác từ blackbox
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: bind-mco-allowlist-probe-metrics
  namespace: rhacm-policies
placementRef:
  name: hub-only
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: mco-allowlist-probe-metrics
  kind: Policy
  apiGroup: policy.open-cluster-management.io
