apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: all-child-clusters
  namespace: rhacm-policies
  labels:
    cluster.open-cluster-management.io/placement: all-child-clusters
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: Exists
