apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: probe-apiserver
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: monitoring.coreos.com/v1
        kind: Probe
        metadata:
          name: openshift-apiserver-healthz
          namespace: openshift-monitoring
        spec:
          jobName: blackbox-exporter
          module: http_2xx
          interval: 30s
          prober:
            url: http://prometheus-blackbox-exporter.openshift-monitoring.svc.cluster.local:9115
          targets:
            staticConfig:
              static:
                - https://apiserver.openshift-kube-apiserver.svc.cluster.local/healthz
              labels:
                app: openshift-apiserver
                cluster: {{hub fromManagedClusterName}}
          tlsConfig:
            insecureSkipVerify: true
